export const listedBusinesses = [
  "Senior benefits",
  "Medicare advisors",
  "Senior care",
  "Senior saving center",
  "USA saving center",
  "Linguistics incorporation",
]
export const partners = [
  "21st Century Insurance",
  "A&B Insurance and Financial",
  "AAA Insurance Co.",
  "AARP",
  "Abrazo Health",
  "ABS Healthcare",
  "Acceptance",
  "Accuquote",
  "Acquisition Technologies",
  "Admaric",
  "Admaric Insurance Agency",
  "Admediary",
  "Admiral Life",
  "Advantra",
  "Advocate Health",
  "Aegis First",
  "Aegon US Holding Corp.",
  "Aetna",
  "Affordable Health Insurance Group",
  "AFLAC",
  "AGA",
  "AgedLeadStore.com",
  "AHCP",
  "AHIA",
  "AHIX",
  "AIG",
  "AIG Direct",
  "AIP",
  "AIS",
  "AIU Insurance",
  "All Digital Promotions",
  "All Web Leads",
  "Allegiant Group",
  "Alliance & Associates",
  "Alliance Insurance",
  "Alliance National Health",
  "Allied",
  "Allied Health",
  "Allied Insurance",
  "Allied Insurance Partners",
  "Allina Health",
  "Allstarz",
  "Allstate County Mutual",
  "Allstate Indemnity",
  "Allstate Insurance",
  "AllWebLeads",
  "America Direct",
  "America's Insurance",
  "American",
  "American Automotive Alliance",
  "American Automobile Insurance",
  "American Benefits Group",
  "American Casualty",
  "American Continental",
  "American Deposit Insurance",
  "American Direct Business Insurance",
  "American Empire Insurance",
  "American Family",
  "American Family Insurance",
  "American Family Mutual",
  "American Fidelity Corp.",
  "American Financial",
  "American General",
  "American Health Underwriters",
  "American Home Assurance",
  "American Insurance",
  "American Insurance Agencies Direct",
  "American Insurance Organization",
  "American Insurance Organization",
  "LLC",
  "American International Ins",
  "American International Pacific",
  "American International South",
  "American Life & Health",
  "American Manufacturers",
  "American Mayflower Insurance",
  "American Motorists Insurance",
  "American National Insurance",
  "American Premier Insurance",
  "American Protection Insurance",
  "American Republic",
  "American Republic Insurance Co.",
  "American Savers Plan",
  "American Security Insurance Company",
  "American Service Insurance Agency",
  "American Skyline Insurance Company",
  "American Spirit Insurance",
  "American Standard Insurance - OH",
  "American Standard Insurance - WI",
  "Americare Group",
  "Americare/American Enterprise",
  "Americas Health Brokers",
  "Americas Health Group",
  "America\u2019s Health Advisors",
  "America\u2019s Trust",
  "Inc.",
  "AmeriChoice",
  "Americo",
  "Amerigroup",
  "AmeriHealth",
  "Amerilife",
  "AmeriPlan",
  "Ameriprise",
  "Ameriprise Financial Group",
  "Ameriquote",
  "Amica",
  "Amica Insurance",
  "Angelic Marketing Group",
  "ANPAC",
  "Answer Financial",
  "Anthem",
  "Anthem / BCBS",
  "Anthem BCBS",
  "Anthem/BCBS",
  "AON",
  "Aon Corp.",
  "Apliant",
  "Apollo Interactive",
  "Arbella",
  "Ardent Health Services",
  "Associated Indemnity",
  "Assurance IQ",
  "Inc.",
  "Assurant",
  "Assurant",
  "Bankers Life and Casualty",
  "Assured Life",
  "Astonish",
  "Atlanta Casualty",
  "Atlantic Blue Media",
  "Atlantic Health",
  "Atlantic Indemnity",
  "Atomic Leads",
  "Audience Serv",
  "Auto Club Insurance Company",
  "Auto Insurance Guide",
  "Auto Owners",
  "Avenge Digital",
  "Aviva",
  "Avmed",
  "AvMed Inc.",
  "AXA Advisors",
  "AXA Insurance Group",
  "Banker's Fidelity",
  "Bankers Life and Casualty",
  "Bankrate",
  "Bankrate Insurance",
  "Bankrate",
  "Inc.",
  "Banner Life",
  "Bantam Connect",
  "Bartleson Brokers",
  "BBRS Group",
  "BCBS",
  "BCBS of Florida",
  "BCBS of Michigan",
  "Beacon Leads",
  "LLC",
  "Benefit Advisors",
  "Benefit Mall",
  "Benepath",
  "Best Agency USA",
  "BestQuotes",
  "BH Insurance Solutions",
  "LLC",
  "Blue Cross",
  "Blue Cross of South Carolina",
  "Blue Cross/Blue Shield Association Companies",
  "Blue Ink Digital",
  "Blue Shield of California",
  "Blue Wing Ads",
  "BlueCross/Blue Sheild Association Companies",
  "BMP Insurance",
  "Bold Media Group",
  "Bold Media Group",
  "Bolt",
  "Boost Health",
  "Bravo Health",
  "Brightway",
  "Bristol West Insurance",
  "Brooke Insurance",
  "Brookstone Financial",
  "BRXTN Digital Media",
  "Btel",
  "Btel Communications",
  "Budget Family Insurance",
  "c0aster",
  "Cal Farm Insurance",
  "California State Automobile Association",
  "Call Center Partnerships",
  "Call4SeniorSavings.com",
  "Cambia",
  "CAN",
  "CancerInsurance.com",
  "Capital Choice",
  "Capital District Physicians Health Plan",
  "Capital Health Insurance of America",
  "CareMore",
  "Caresource",
  "Carle Clinic Association",
  "Catholic Financial Life",
  "CDPHP",
  "Cege Media",
  "Centene",
  "Centene Corp.",
  "Century Benefits",
  "Cherry Blitz",
  "Choice Direct",
  "Choice Direct",
  "Choice Insurance",
  "Christian Fidelity",
  "Chubb",
  "Cigna",
  "Cigna",
  "Coventry",
  "Fortis",
  "Citigroup",
  "Citirex",
  "Citizens",
  "Clarendon American Insurance",
  "Clarendon National Insurance",
  "Clear One",
  "Clearlink",
  "CNA Insurance",
  "CO Farm Bureau",
  "Colonial Insurance",
  "Colonial Penn",
  "Commercial Marketing Group",
  "CommercialInsurance.net",
  "Community Care",
  "CommunityCare",
  "Compare.com",
  "Comparison Market",
  "Connect Insurance Brands",
  "Connect One Health",
  "Connect Plus",
  "Connect Rite Bpo",
  "ConnectiCare",
  "Conseco Life",
  "Consumer United",
  "Contactability",
  "Continental Casualty",
  "Continental Divide Insurance",
  "Continental Insurance",
  "Continental Life",
  "Conventry",
  "Corner Shop Media",
  "Cotton States Insurance",
  "Country Companies",
  "Country Financial",
  "Country Insurance and Financial Services",
  "Countrywide Insurance",
  "Coventry",
  "Coventry Health Care",
  "Coverage One",
  "Coverage One Insurance Group LLC",
  "Coverage One Insurance Group",
  "LLC",
  "Coverdell",
  "CoverHound",
  "Covida",
  "Creative Emarketing",
  "Crosspointe Insurance Advisors",
  "CS Marketing",
  "CSE",
  "CSE Insurance Group",
  "CUNA Mutual Group",
  "Dairyland County Mutual Co of TX",
  "Dairyland Insurance",
  "Datalot",
  "Datalot",
  "DataMax",
  "Datwerx",
  "Dean Health",
  "Delphi Financial",
  "Digiline Media",
  "Digital DBA",
  "Direct Auto",
  "Direct Choice",
  "Direct General",
  "Direct Property & Casualty",
  "Direct Ring Media",
  "Direct Web Advertising",
  "Discount Insurance Quotes",
  "Dobak Holdings LLC",
  "Doc Auto Insurance",
  "Donisi Jax Inc.",
  "DoublePositive",
  "DTRIC",
  "E-Telequote",
  "e-TeleQuote Insurance",
  "e-TeleQuote Insurance",
  "Inc.",
  "Eagle Health",
  "eAmerifamily",
  "East Coast Health Insurance",
  "Efinancial",
  "eHealth Insurance",
  "eHealthInsurance Services",
  "Elderplan",
  "Electric",
  "Electric Insurance",
  "Elephant",
  "EmblemHealth",
  "Empire",
  "Encompass",
  "Energy Alliance",
  "Enrollment Services Inc.",
  "EPIQ",
  "Equita Group",
  "Equita Group Final Expense Services",
  "Erie Insurance Company",
  "Erie Insurance Exchange",
  "Erie Insurance Group",
  "Erie Insurance Property and Casualty",
  "Esurance",
  "Everest Financial & Insurance Services",
  "Every Choice Insurance",
  "EverQuote Inc.",
  "EverQuote marketing partners",
  "Exact Match Media",
  "Excel Impact",
  "Excella Benefits",
  "Inc.",
  "Excelling",
  "Inc.",
  "Excellus",
  "Fallon Community Health Plan",
  "Family First Insurance Advisors",
  "Family Life",
  "Family/Rural",
  "Farm Bureau",
  "Farm Bureau/Farm",
  "Farmers Insurance",
  "Farmers Union",
  "Fidelis",
  "Fidelity Life",
  "Field of Leads Ltd.",
  "Fields of Leads",
  "FinanceBox.com",
  "Fiorella Insurance",
  "Fire and Casualty Insurance Co of CT",
  "Fireman's Fund",
  "First Choice Health",
  "First Family Insurance",
  "First Preferred Insurance",
  "Flexquote",
  "Florida Blue",
  "Florida First Insurance Agency",
  "Flyhigh",
  "Forefront Insurance",
  "Foremost Insurance",
  "Foresters",
  "Forethought",
  "Formza",
  "LLC",
  "Fortegra Insurance",
  "Fortis",
  "Freedom health",
  "Freeway Insurance",
  "GAINSCO",
  "Gaurantee Trust Life",
  "Geber Life",
  "GEICO",
  "Geico Casualty",
  "Geico General Insurance",
  "Geico Indemnity",
  "Geisinger",
  "Geisinger Insurance",
  "Generation Life",
  "Genworth",
  "Genworth Financial",
  "Gerber",
  "Gerber Life",
  "Get My Life Insured",
  "Get Seen Media",
  "GetAuto",
  "GetInsured",
  "GetMeHealthCare.com",
  "GHI",
  "GigUp",
  "Globalsky BPO",
  "Globe Life",
  "GMAC Insurance",
  "GMAC/NGIC",
  "Go Direct Lead Generation",
  "LLC",
  "GoHealth",
  "GoHealth/Norvax",
  "GoHealthInsurance.com",
  "Goji",
  "Golden Rule",
  "Golden Rule Insurance",
  "Golden Rule Insurance Co.",
  "GoMedigap",
  "Government Employees Insurance",
  "Government Personnel Mutual Life",
  "Great American",
  "Great West",
  "GreatAmerican",
  "Grey Peaks",
  "Group Health Incorporated",
  "Guaranteed Benefits",
  "Guaranteed Health Options",
  "Guaranty National Insurance",
  "Guardian Healthcare",
  "Guardian Life",
  "Guide One",
  "Guide One Insurance",
  "Guide to Insure",
  "Guide to Insure",
  "GuidePointe Solutions",
  "Hanover",
  "Hanover Lloyd's Insurance Company",
  "HAP Health Alliance",
  "Hartford",
  "Hartford Accident and Indemnity",
  "Hartford Casualty Insurance",
  "Hartford Fire & Casualty",
  "Hartford Fire Insurance",
  "Hartford Insurance Co of Illinois",
  "Hartford Insurance Co of the Southeast",
  "Hartford Life",
  "Hartford Omni",
  "Hartford Underwriters Insurance",
  "Harvard Commonwealth Health Plan",
  "Harvard Pilgrim",
  "HasTraffic",
  "Hawaii Medical Services Association",
  "HCC Insurance holdings",
  "Health & Life Advantage",
  "Health America",
  "Health and Life Associates",
  "Health and Life Plans of America",
  "Health Benefits Center",
  "Health Benefits Direct",
  "Health Benefits One",
  "Health Care Service Corp.",
  "Health Choice One",
  "Health Corp USA",
  "Health Dime",
  "Health I.Q.",
  "Health Insurance for Everyone",
  "Health Insurance Innovations",
  "Health Insurance of America",
  "Health Insurance Services",
  "Health Markets",
  "Health Net",
  "Health Now New York Inc.",
  "Health Option One",
  "Health Partners of Philadelphia Inc.",
  "Health Plan One",
  "Health Plans of America",
  "Health Plus",
  "Health Plus of America",
  "Health Savings Group",
  "Health1nsurance.com",
  "Healthcare Advisors",
  "HealthCare Alternatives",
  "Healthcare Direct",
  "Healthcare Solutions Team",
  "Healthcare.com",
  "HealthCompare Insurance Services",
  "Inc.",
  "HealtheDeals",
  "HealthInsurance.net",
  "HealthIQ",
  "HealthMarkets",
  "HealthMarkets / Insphere",
  "HealthMarkets/Insphere",
  "HealthMatchup",
  "HealthNet",
  "HealthPartners",
  "HealthPlan Advisors",
  "HealthPlanMatchup",
  "HealthPlanOne",
  "HealthPlus of Michigan",
  "HealthPocket",
  "HealthQuoteInfo.com",
  "HealthShare American",
  "HealthSpire",
  "HealthSpring",
  "Healthy Halo",
  "Henry Ford Health System",
  "Heritage Health Advisors",
  "Highmark",
  "Highmark BCBS",
  "HIP Health Plan",
  "HIP Insurance",
  "Hippo Insurance",
  "Hiscox",
  "HK Flavors Limited",
  "HolaDoctor",
  "Home Bundles",
  "Home Insurance King",
  "Home Path",
  "Home Savings",
  "HomeBundles",
  "Homeinsurance.com",
  "Homeland HealthCare",
  "Hometown Quotes",
  "Horace Mann",
  "Horizon",
  "Hospital Services Association of NEPA",
  "HPO",
  "HST",
  "HST Enrollment Center",
  "Humana",
  "Hypertarget Marketing",
  "iCan Benefit",
  "iCan Benefit Group",
  "Ideal Concepts",
  "Ideal Concepts",
  "Inc",
  "IFA Auto Insurance",
  "IGF Insurance",
  "IHC Group",
  "IHC Health Plans",
  "IMO",
  "Impact Media",
  "Independence Blue Cross",
  "Independent Carriers",
  "Independent Health Association",
  "Independent Insurance Consultants",
  "Infinity Insurance",
  "Infinity National Insurance",
  "Infinity Select Insurance",
  "Infinix Media",
  "ING",
  "ING US Life",
  "Innovate Financial Group",
  "Innovation Direct Group",
  "Inquire Media",
  "Inside Response",
  "Insphere",
  "Insphere Insurance Solutions",
  "InsuraMatch",
  "Insurance311",
  "Insurance Care Direct",
  "Insurance Central",
  "Insurance Insight",
  "Insurance Line One",
  "Insurance Made Easy",
  "Insurance Management Associates",
  "Insurance Services",
  "Insurance Solutions Direct",
  "Insurance Solutions LLC",
  "Insurance.com",
  "InsuranceLeads.com",
  "InsuranceOnly",
  "InsuranceProz",
  "InsuranceQuotes",
  "Inc.",
  "insuranceQuotes.com",
  "Insure.com",
  "Insured Street",
  "InsureMe",
  "InsWeb",
  "Integon",
  "Integrated Benefits",
  "IntelliQuote",
  "Inter Valley Health Plan",
  "IPA Direct",
  "iQuoteX",
  "Jackson National Life",
  "JCG New Media",
  "JLS",
  "John Hancock",
  "JRC Insurance Group",
  "Kaiser",
  "Kaiser Permanente",
  "Kaiser",
  "Medicare Solutions",
  "Kallstar",
  "Kanopy",
  "Kanopy Insurance",
  "Kanopy Insurance Center LLC",
  "Keenan Associates",
  "Kelsey-Seybold",
  "Kemper",
  "Kemper Lloyds Insurance",
  "Key Insurance Advisors",
  "Keystone",
  "Knights of Columbus",
  "Landmark American Insurance",
  "Lands Health",
  "LBCOT Insurance",
  "Lead Foundations",
  "Lead Origins",
  "Lead Trust Media Group",
  "Leadco",
  "LeadEnvoy",
  "Leader National Insurance",
  "Leader Preferred Insurance",
  "Leader Specialty Insurance",
  "Leadnomics",
  "Legal & General America",
  "Lemonade Insurance Agency",
  "LLC",
  "Lender Daily Corp",
  "Level One Health Group",
  "Liberty First Health and Life",
  "Liberty Health Plan",
  "Liberty Insurance Corp",
  "Liberty Mutual",
  "Liberty Mutual Fire Insurance",
  "Liberty Mutual Insurance",
  "Liberty Mutual Insurance Company",
  "Liberty National",
  "Liberty Northwest Insurance",
  "LifeInsuranceMatchup",
  "LifeLine Direct",
  "LifeQuotes",
  "Lifetime Healthcare",
  "Lighthouse Insurance Group",
  "Lincoln National",
  "Line East Leads",
  "ListenClear",
  "Lockton Affinity Group",
  "Longevity Alliance",
  "Louisiana Health Services",
  "Loyal American",
  "LQ Digital",
  "Lumbermens Mutual",
  "M Plan Inc.",
  "Managed Health Inc.",
  "MAPFRE",
  "Marchex",
  "Martin's Point",
  "Martinez Insurance Group Inc",
  "Maryland Casualty",
  "Mass Mutual",
  "Massachusetts Mutual",
  "Massive&Co",
  "MassNexus",
  "Match Media Group",
  "LLC",
  "Matrix Warranty Solutions",
  "Maxxlocal",
  "MedGapDirect",
  "MediaAlpha",
  "Medical Card System Inc.",
  "Medical Mutual of Ohio",
  "Medicare Solutions",
  "MedicareAdvantage.com",
  "MedicareProz",
  "Mega/Midwest",
  "Mercury",
  "Mercy",
  "Metlife",
  "MetLife Auto and Home",
  "Metropolitan Insurance Co.",
  "Mid-Continent Casualty",
  "Middlesex Insurance",
  "Midland National",
  "Midland National Life",
  "Migo Insure",
  "Mikayla Data",
  "Minnesota Mutual",
  "Mississippi Insurance",
  "MJ Direct",
  "MMI Group",
  "MMM Healthcare Inc.",
  "Modern Health",
  "LLC",
  "Molina",
  "Molina Healthcare Inc.",
  "Moss Affiliate Marketing",
  "Mountain Financial",
  "Mutual of New York",
  "Mutual of Omaha",
  "MVP",
  "MyHealthAngel.com",
  "MyInsuranceExpert",
  "National Ben Franklin Insurance",
  "National Better Living Association",
  "National Brokerage",
  "National Brokers of America",
  "National Casualty",
  "National Continental Insurance",
  "National Family Assurance Group",
  "Inc.",
  "National Fire Insurance Company of Hartford",
  "National General Insurance",
  "National Health Connect",
  "National Health Connect LLC",
  "National Health Hub LLC",
  "National Health Insurance",
  "National Health Plans dba Your Lowest Quote",
  "National Health Solutions",
  "National Healthcare Advisors",
  "National Indemnity",
  "National Union Fire Insurance of LA",
  "National Union Fire Insurance of PA",
  "Nations Health Group Guide One Insurance",
  "Nations Insurance Solutions",
  "Nationwide",
  "Nationwide General Insurance",
  "Nationwide Health Advisors",
  "Nationwide Insurance Company",
  "Nationwide Mutual Fire Insurance",
  "Nationwide Mutual Insurance",
  "Nationwide Property and Casualty",
  "Navy Mutual Aid Association",
  "Neighborhood Health Plan Inc.",
  "Neilson Financial Services",
  "Net Health Affiliates",
  "NetQuote",
  "New England Financial",
  "New Era",
  "New York Life",
  "New York Life Insurance",
  "NewQuest",
  "Next Gen",
  "Next Wave Marketing",
  "Next Wave Marketing Strategies",
  "Inc",
  "NextGen Leads",
  "NGIC",
  "Nikia Media",
  "NMP Insurance Services",
  "LLC / NameMyPremium",
  "Noridian Mutual Insurance Company",
  "Northwest Medical",
  "Northwestern Mutual",
  "Northwestern Mutual Life",
  "Northwestern Pacific Indemnity",
  "Norvax",
  "NuHealth",
  "Number One Health Insurance Agency",
  "OctaneFire",
  "Offer Advisors",
  "OfferWeb.com",
  "Ohio National Life",
  "Old Mutual US Life",
  "Omni Indemnity",
  "Omni Insurance",
  "ompareInsuranceQuotes",
  "ONCOR Insurance Services",
  "Onviant",
  "Onyx Digital Media",
  "Optimize.Ad",
  "Optimum HealthCare",
  "Orion Insurance",
  "OSCAR Health",
  "Oscar Health Insurance",
  "Oxford",
  "Pacific Benefits Group",
  "Pacific Indemnity",
  "Pacific Insurance",
  "Pacific Life",
  "Pacific Life and Annuity",
  "Pacificare",
  "Pafco General Insurance",
  "Palmetto Senior Solutions",
  "Parachute Insurance Services Corp",
  "Parasol Agents Network",
  "Patriot General Insurance",
  "Pay Per Call Market",
  "Peace of Mind Solutions",
  "Peak Performance",
  "Peak Property and Casualty Insurance",
  "Pemco",
  "PEMCO Insurance",
  "Penn Mutual",
  "Phoenix Life",
  "Physicians Health Plan",
  "Physicians Life",
  "Physicians Mutual",
  "Physicians United Plan",
  "Pickett Group/TermLifeMatch",
  "Pier21 Media",
  "Ping Leads",
  "Pinney Insurance Center",
  "Inc.",
  "PJP Agency",
  "PJP Health",
  "Platinum Leads",
  "Plymouth Rock",
  "PMIC",
  "Policy Fuel",
  "Powderhorn Media",
  "Power Source Marketing",
  "Practical Marketing",
  "Precise Leads",
  "Precise Solutions Group",
  "Precursor Media",
  "Preferred Care",
  "Preferred Mutual",
  "Premera Blue Cross",
  "Premier Business Solutions",
  "Premier Health Solutions",
  "Premium Precision Marketing",
  "Presbyterian Health Plan",
  "Presbyterian Healthcare Services",
  "Presidio Interactive",
  "Presidio Interactive Corp",
  "Primary Health Care",
  "Prime Care Health",
  "Prime Marketcare One",
  "Principal",
  "Principal Financial",
  "Principal Life",
  "Priority Health",
  "Progressive",
  "Progressive Auto Pro",
  "Progressive Insurance",
  "Progressive Motorcycle",
  "Protective Life",
  "Providence",
  "Providence Health Plan",
  "Prudential",
  "Prudential Insurance Co.",
  "Prudential of America",
  "PURE",
  "Puritan Health",
  "PX",
  "Pyramid Life",
  "Qatalyst",
  "Quality Healthcare Solutions",
  "Quick Life Center",
  "LLC",
  "QuickInsured",
  "QuickQuote",
  "QuinStreet",
  "Quote Engine",
  "Quote Storm Holdings",
  "LLC",
  "QuoteLab",
  "LLC",
  "QuoteStorm",
  "QuoteWhiz",
  "QuoteWizard",
  "Rank Media",
  "Real Results",
  "RedVentures",
  "Regence",
  "Reliance Insurance",
  "Reliance National Indemnity",
  "Reliance National Insurance",
  "ReliaQuote",
  "Renaissance Health Services Corp.",
  "Republic Indemnity",
  "Response Insurance",
  "ReviMedia",
  "RevPoint Media",
  "Rex Direct",
  "Ring Router",
  "Rogue E-Cigs",
  "RSA",
  "Safe Auto",
  "Safeco",
  "Safeguard",
  "SafeguardCasualty Inc",
  "Safeway",
  "Safeway Insurance",
  "Safeway Insurance Co of AL",
  "Safeway Insurance Co of GA",
  "Safeway Insurance Co of LA",
  "Sagicor",
  "Savings Bank Life Insurance Company of Massachusetts (SBLI)",
  "Scan Health Plan",
  "SCMS",
  "Scott and White",
  "Seascape",
  "Seascape Health",
  "Seascape Life",
  "Secure Horizons",
  "Secured Health",
  "Security Health Plan of Wisconsin Inc.",
  "Security Insurance Co of Hartford",
  "Security National Insurance Co of FL",
  "SelectHealth",
  "Selective Healthcare",
  "SelectQuote",
  "SelectQuote Insurance Services",
  "SelectQuote Life",
  "SelectQuote Senior",
  "Senior Health Connect Insurance Agency",
  "Senior Health Direct",
  "Senior Healthcare Direct",
  "Senior Market Partners",
  "Senior Market Sales",
  "SeniorCare Benefits",
  "SeniorQuote Insurance Services",
  "Sentara Health Management",
  "Sentinel Insurance",
  "Sentry",
  "Sentry Insurance a Mutual Company",
  "Sentry Insurance Company",
  "Sentry Insurance Group",
  "Shelter Insurance Co.",
  "Shelter Insurance Company",
  "Sierra Health Services",
  "Simple Health",
  "Simple Health Plans Inc.",
  "Simple Insurance Leads",
  "Simpson Financial Group",
  "Singularity Media",
  "Smart Match Insurance Solutions",
  "Smedley Insurance Group",
  "SolarJoy",
  "SolidQuote",
  "SolidQuote",
  "LLC",
  "Southern Guard Insurance",
  "Spectrum Direct",
  "Spectrum Health",
  "Spring Insurance Solutions",
  "Spring Venture Group",
  "SS Telemarketing",
  "St. Paul",
  "St. Paul Fire and Marine",
  "St. Paul Insurance",
  "Stancorp Financial",
  "Standard Fire Insurance Company",
  "Standard Life",
  "State and County Mutual Fire Insurance",
  "State Auto",
  "State Farm",
  "State Farm County",
  "State Farm Fire and Cas",
  "State Farm General",
  "State Farm Indemnity",
  "State Farm Insurance Co.",
  "State Farm Lloyds Tx",
  "State Farm Mutual Auto",
  "State Fund",
  "State National Insurance",
  "Sterling",
  "Sterling Senior Health",
  "Stone Hill National",
  "SubjectWell",
  "Suited Connector",
  "SummaCare",
  "Summit Health",
  "Sun Coast",
  "Sun Life Assurance Company",
  "Sunrise Health",
  "Superior American Insurance",
  "Superior Guaranty Insurance",
  "Superior Insurance",
  "Support First",
  "Sure Health Plans",
  "Sureco",
  "SVG",
  "Swiss Re",
  "Tallac Media",
  "Tech Insurance",
  "TexanPlus",
  "The Ahbe Group",
  "The Benefit Depot",
  "The Benefit Link",
  "The Complete Lead",
  "The General",
  "The Hartford",
  "The Hartford AARP",
  "The Insurance Center",
  "The Lead Company",
  "The Senior Resource Group",
  "The Zebra",
  "Three Rivers Holdings",
  "Thrivent Financial for Lutherans",
  "TIAA-CREF",
  "Tiburon Insurance Services",
  "TICO Insurance",
  "TIG Countrywide Insurance",
  "Titan",
  "Tobias & Associates",
  "Torchlight Technology",
  "Torchmark",
  "Touchstone",
  "Towers Watson dba OneExchange",
  "TPG Direct",
  "Traders Insurance",
  "Transamerica",
  "Travelers",
  "Travelers Indemnity",
  "Travelers Insurance",
  "Travelers Insurance Company",
  "Tri-State Consumer Insurance",
  "Triple-S Inc.",
  "TriState",
  "TruBridge",
  "Inc.",
  "TruSource Marketing",
  "Tryton",
  "TSC Insurance",
  "Tufts",
  "Tufts Associates HMO Inc.",
  "TWG",
  "Twin City Fire Insurance",
  "TZ Insurance Solutions LLC",
  "Ucare",
  "UMA",
  "Underground Elephant",
  "UniCare",
  "Unique Q2B",
  "United American/Farm and Ranch",
  "United Healthcare",
  "United Healthcare Advisors",
  "United Medicare",
  "United Medicare Advisors",
  "United of Omaha",
  "United Pacific Insurance",
  "United Security",
  "United Services Automobile Association",
  "UnitedHealthcare/UnitedHealthOne",
  "Unitrin",
  "Unitrin Direct",
  "Universal American",
  "Universal American Financial Corp.",
  "Universal Health Care",
  "Universal Healthcare Advisors",
  "Universal Underwriters Insurance",
  "University Health Care Inc.",
  "UnumProvident Corp.",
  "UPMC",
  "UPMC Health System",
  "US Benefit Solutions",
  "US Financial",
  "US Financial Life",
  "US Health Advisors",
  "US Web Leads",
  "USA Benefits/Continental General",
  "USA Dental Club",
  "USAA",
  "USF and G",
  "USHEALTH Group",
  "USInsuranceOnline",
  "Valiant Acquisition Corp",
  "Vanguard Health Ventures",
  "Vantis Life",
  "Velapoint",
  "VelaPoint Personal Insurance",
  "Verified Insurance Lead",
  "Versible Connect",
  "Versus Media Group",
  "Verti Insurance",
  "Vertigen LLC",
  "Viking County Mutual Insurance",
  "Viking Insurance Co of WI",
  "VIMO",
  "Visiqua",
  "Visiqua",
  "Vital One Health Plans Direct",
  "LLC",
  "VitalOne Health Plans",
  "Viva Health",
  "Voxify",
  "Voxify LLC",
  "Washington National Life",
  "We Speak",
  "WEA Inc.",
  "WebAdGurus.com Inc",
  "WebTec",
  "Wejo",
  "Wellcare",
  "WellCare Health Plans",
  "WellPoint",
  "Western & Southern Life",
  "Western and Southern Life",
  "Western Mutual",
  "Wheaten Worldwide",
  "Windsor Insurance",
  "Woodlands Financial Group",
  "World of Insurance",
  "WynnHealth",
  "XLHealth",
  "Yasha Marketing",
  "YourHealthCareQuotes.com",
  "Zander",
  "Zebra",
  "Zoom Insurance",
  "ZQ Sales",
  "Zurich",
  "Zurich North America or other partners",
]
