import ProgressiveLogo from "../assets/ProgressiveLogo.png"
import StateFarmLogo from "../assets/StateFarmLogo.png"
import GiecoLogo from "../assets/GiecoLogo.png"
import LibertyLogo from "../assets/libertyLogo.png"
import FiremanLogo from "../assets/firemanLogo.png"

export const autoInsImages = [
  LibertyLogo,
  FiremanLogo,
  StateFarmLogo,

  ProgressiveLogo,
  GiecoLogo,
]
export const carArr = [
  {
    Buick: ["Allure/Lacrosse", "Enclave", "Lacrosse", "Lucernce"],
  },
  {
    Chevrolet: [
      "3500",
      "4500",
      "4500HD",
      "4500XD",
      "5500HD",
      "5500XD",
      "6500XD",
      "BOLT EV",
      "Blazer",
      "Bolt Euv",
      "Colorado",
      "Corvette",
      "Equinox",
      "Express G2500",
      "Express G3500",
      "Express G4500",
      "Malibu",
      "Silverado",
      "Silverado Ltd",
      "Spark",
      "Suburban",
      "Tahoe",
      "Trailblazer",
      "Traverse",
      "Trax",
      "Avalanche",
      "Aveo",
      "Camaro",
      "Cobalt",
    ],
  },
  {
    Chrysler: ["300", "300C", "Pacifica", "Voyager"],
  },
  {
    Dodge: ["Challenger", "Charger", "Durango", "Grand Caravan", "Journey"],
  },
  {
    Ford: ["Challenger", "Charger", "Durango", "Grand Caravan", "Journey"],
  },
  {
    GMC: [
      "Ecosport",
      "Edge",
      "Escape",
      "Expedition",
      "Explorer",
      "F150",
      "F250",
      "F350",
      "F450",
      "F53",
      "F550",
      "F59",
      "F600",
      "Figo",
      "Fusion",
      "GT",
      "Mustang",
      "Ranger",
      "Transit",
      "Transit Connect",
    ],
  },
  {
    Honda: [
      "Accord",
      "Civic",
      "Clarity",
      "Cr-V",
      "Fit",
      "Hr-V",
      "Insight",
      "Odyssey",
      "Passport",
      "Pilot",
      "Ridgeline",
    ],
  },
  {
    Hyundai: [
      "Accent",
      "Elantra GT",
      "Elantra",
      "Ioniq",
      "Kona",
      "Nexo",
      "Palisade",
      "Santa Fe",
      "Santa Fe XI",
      "Sonata",
      "Veloster",
      "Veloster N",
      "Venue",
    ],
  },
  {
    Jeep: [
      "Cherokee",
      "Compass",
      "Gladiator",
      "Grand Cherokee",
      "Renegade",
      "Wrangler",
      "Wrangler Unlimited",
    ],
  },
  {
    Kia: [
      "Cadenza",
      "Forte",
      "K900",
      "Niro",
      "Optima",
      "Rio",
      "Soul EV",
      "Sedona",
      "Sorento",
      "Soul",
      "Sportage",
      "Stinger",
      "Telluride",
    ],
  },
  {
    Nissan: [
      "370Z",
      "Altima",
      "Armada",
      "Frontier",
      "GT-R",
      "Kicks",
      "Leaf",
      "Maxima",
      "Micra",
      "Murano",
      "NV",
      "NV-200",
      "PathFinder",
      "Rogue",
      "Rogue Sport",
      "Sentra",
      "Titan XD",
      "Titan",
      "Versa",
    ],
  },
  {
    Toyota: [
      "4RUNNER",
      "86",
      "Avalon",
      "C-Hr",
      "Camry",
      "Corolla",
      "Highlander",
      "Land Cruiser",
      "Mirai",
      "Prius",
      "Prius C",
      "Prius Prime",
      "Sequoia",
      "Sienna",
      "Supra",
      "Tacomma",
      "Tundra",
      "Yaris",
    ],
  },

  {
    Acura: ["ILX", "MDX", "NSX", "RDX", "RLX", "TLX"],
  },
  {
    "Aston Martin": [
      "DB11",
      "Dbs",
      "Rapide",
      "V12 Vantage",
      "V8",
      "Vanquish",
      "Vantage",
    ],
  },
  {
    Audi: [
      "A3",
      "A4",
      "A4 Allroad",
      "A5",
      "A6",
      "A6 Allroad",
      "A7",
      "A8",
      "E-Tron",
      "Q3",
      "Q5",
      "Q5E",
      "Q7",
      "Q8",
      "R7",
      "R8",
      "RS3",
      "RS5",
      "RS Q8",
      "S3",
      "S4",
      "S5",
      "S6",
      "S7",
      "S8",
      "SQ5",
      "SQ7",
      "SQ8",
      "TT",
      "TT RS",
      "TTS",
    ],
  },
  {
    Bentley: ["Bentayga", "Continental", "Flying Spur", "Mulsanne"],
  },
  {
    BMW: [
      "228xi",
      "230i",
      "230xi",
      "330i",
      "330xi",
      "430i",
      "430xi",
      "440i",
      "440xi",
      "530",
      "530e",
      "530xe",
      "540",
      "540xd",
      "640",
      "650",
      "740",
      "745xe",
      "740",
      "745xe",
      "750",
      "840i",
      "Sienna",
      "840xi",
      "Alpina B6",
      "Alpina B7",
      "i3",
      "i8",
      "M2",
      "M235xi",
      "M240i",
      "M240xi",
      "M340i",
      "M340xi",
      "M4",
      "M5",
      "M550xi",
      "M6",
      "M760",
      "M8",
      "M850xi",
      "X1",
      "X2",
      "X3",
      "X4",
      "X5",
      "X6",
      "X7",
      "Z4",
    ],
  },
  {
    Caddilac: [
      "CT6",
      "CT4",
      "CT4-V",
      "CT5",
      "CT5-V",
      "CT6-V",
      "Escalade",
      "XT5",
      "XT4",
      "XT6",
    ],
  },
  {
    " McLaren Automotive": [
      "540C",
      "570GT",
      "570S",
      "600LT",
      "620R",
      "720S",
      "765LT",
      "GT",
      "Senna GTR",
      "Speedtail",
    ],
  },
  {
    Ferrari: [
      "488 GTB",
      "488 Pista",
      "488 Pista Spider",
      "488 GTB",
      "488 Spider",
      "812 Superfast",
      "F8 Tributo",
      "GTC 4 LUSSO T",
      "GTC 4 LUSSO",
      "Portofino",
    ],
  },
  {
    Hummer: ["H1", "H2"],
  },
  {
    Infinity: ["Q50", "Q60", "Q70", "Q70i", "QX50", "QX60", "QX80"],
  },
  {
    Isuzu: ["FTR", "NPR HD", "NQR", "NRR"],
  },
  {
    Jaguar: ["E-Pace", "F-Pace", "I-Pace", "F-Type", "XE", "XF", "XJ", "XJL"],
  },
  {
    Lamborghini: ["Aventador", "Huracan", "Urus"],
  },
  {
    "Land Rover": [
      "Defender",
      "Discovery",
      "Discovery Sport",
      "Range Rover",
      "Range Rover Evoque",
      "Range Rover Sport",
      "Range Rover Velar",
    ],
  },
  {
    Lexus: [
      "ES",
      "GS",
      "IS",
      "LS",
      "GS-F",
      "GX",
      "LC",
      "LX",
      "NX",
      "RC",
      "RC-F",
      "RX",
      "UX",
    ],
  },
  {
    Lincoln: [
      "Aviator",
      "Continental",
      "Corsair",
      "MKZ",
      "Nautilus",
      "Navigator",
    ],
  },
  {
    Lotus: ["Evora"],
  },
  {
    Maserati: ["Ghibli", "Granturismo", "Levante", "Quattroporte"],
  },
  {
    Mazda: ["3", "6", "CX-3", "CX-5", "CX-9", "CX-30", "MX-5 Miata", "Mazda 2"],
  },
  {
    "Mercedes-Benz": [
      "A",
      "AMG GT",
      "B250",
      "C",
      "CLA",
      "CLS",
      "E",
      "G",
      "GLA",
      "GLS",
      "GLC",
      "GLE",
      "GLB",
      "GLC Coupe",
      "Metris",
      "S",
      "SLC",
      "SL",
      "Sprinter",
    ],
  },
  {
    Mercury: ["Capri", "Cougar", "Grand Marquis", "Lynx", "Marquiz", "Topaz"],
  },
  {
    Mini: ["Cooper"],
  },
  {
    Mitsubishi: [
      "Eclipse Cross",
      "Mirage",
      "Outlander",
      "Outlander Sport",
      "RVR",
    ],
  },
  {
    Pontiac: [
      "6000",
      "Acadian",
      "Boneville",
      "Fiero",
      "Firebird",
      "Grand Prix",
      "J2000",
      "Parisienne",
      "Phoenix",
      "T-1000",
    ],
  },
  {
    Porsche: [
      "911",
      "Boxster",
      "Cayenne",
      "Cayman",
      "Maccan",
      "Panamera",
      "Taycan",
    ],
  },
  {
    "Rolls-Royce": ["Cullinan", "Dawn", "Ghost", "Phantom", "Wraith"],
  },
  {
    Saab: ["900"],
  },
  {
    Saturn: ["Ion", "L200", "L300", "Lw200", "LW300", "Vue"],
  },
  {
    Smart: ["Fortwo"],
  },
  {
    Subaru: [
      "Ascent",
      "BRZ",
      "Crosstrek",
      "Forester",
      "Impreza",
      "Legacy",
      "Outback",
      "WRX",
    ],
  },

  {
    Tesla: ["Model 3", "Model S", "Model X", "Model Y"],
  },
  {
    Volkswagen: [
      "Arteaon",
      "Atlas",
      "Atlas Cross Sport",
      "E-Golf",
      "GTI",
      "Golf",
      "Golf R",
      "Golf Sportwagen",
      "Jetta",
      "Passat",
      "Tiguan",
    ],
  },
  {
    Volvo: [
      "9700",
      "S60",
      "S90",
      "V60",
      "V60 Cross Country",
      "V90",
      "V90 Cross Country",
      "VAH",
      "VHD",
      "VN",
      "VNR",
      "XC60",
      "XC90",
      "XC40",
    ],
  },
]

export const insurance = [
  "21st Century Insurance",
  "AAA Insurance Co.",
  "Allstate",
  "American Family",
  "Liberty Mutual",
  "Fireman's Fund",
  "State Farm",
  "Progressive",
  "Geico",
]

export const stateInitials = [
  "AL",
 "AK",
 "AZ",
 "AR",
 "CA",
 "CO",
 "CT",
 "DE",
 "DC",
 "FL",
 "GA",
 "HI",
 "ID",
 "IL",
 "IN",
 "IA",
 "KS",
 "KY",
 "LA",
 "ME",
 "MD",
 "MA",
 "MI",
 "MN",
 "MS",
 "MO",
 "MT",
 "NE",
 "NV",
 "NH",
 "NJ",
 "NM",
 "NY",
 "NC",
 "ND",
 "OH",
 "OK",
 "OR",
 "PA",
 "RI",
 "SC",
 "SD",
 "TN",
 "TX",
 "UT",
 "VT",
 "VA",
 "WA",
 "WV",
 "WI",
 "WY",

]
